name: Publish NuGet Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: true
        default: '1.0.0'

env:
  PROJECT_PATH: src/Http2Client.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          8.0.x
          9.0.x

    - name: Set version from input
      if: github.event_name == 'workflow_dispatch'
      run: dotnet msbuild ${{ env.PROJECT_PATH }} -p:PackageVersion=${{ github.event.inputs.version }}

    - name: Set version from tag
      if: github.event_name == 'release'
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        dotnet msbuild ${{ env.PROJECT_PATH }} -p:PackageVersion=$VERSION

    - run: dotnet restore ${{ env.PROJECT_PATH }}

    - run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - run: mkdir -p ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - run: |
        PKG=$(ls ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg | head -n 1)
        dotnet nuget push "$PKG" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
