name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  PROJECT_PATH: src/Http2Client.csproj

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          8.0.x
          9.0.x
          
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
      
    - name: Create release directories
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "release/netstandard2.0"
        New-Item -ItemType Directory -Force -Path "release/net5.0"
        New-Item -ItemType Directory -Force -Path "release/net6.0"
        New-Item -ItemType Directory -Force -Path "release/net8.0"
        New-Item -ItemType Directory -Force -Path "release/net9.0"
        
    - name: Copy build artifacts
      shell: pwsh
      run: |
        # Copy .NET Standard 2.0
        Copy-Item "src/bin/Release/netstandard2.0/*" "release/netstandard2.0/" -Recurse -Force
        
        # Copy .NET 5.0
        Copy-Item "src/bin/Release/net5.0/*" "release/net5.0/" -Recurse -Force
        
        # Copy .NET 6.0
        Copy-Item "src/bin/Release/net6.0/*" "release/net6.0/" -Recurse -Force
        
        # Copy .NET 8.0
        Copy-Item "src/bin/Release/net8.0/*" "release/net8.0/" -Recurse -Force
        
        # Copy .NET 9.0
        Copy-Item "src/bin/Release/net9.0/*" "release/net9.0/" -Recurse -Force
        
    - name: Create zip archives
      shell: pwsh
      run: |
        Compress-Archive -Path "release/netstandard2.0/*" -DestinationPath "Http2Client-netstandard2.0.zip"
        Compress-Archive -Path "release/net5.0/*" -DestinationPath "Http2Client-net5.0.zip"
        Compress-Archive -Path "release/net6.0/*" -DestinationPath "Http2Client-net6.0.zip"
        Compress-Archive -Path "release/net8.0/*" -DestinationPath "Http2Client-net8.0.zip"
        Compress-Archive -Path "release/net9.0/*" -DestinationPath "Http2Client-net9.0.zip"
        
        # Create combined archive with all frameworks
        Compress-Archive -Path "release/*" -DestinationPath "Http2Client-all-frameworks.zip"
        
    - name: Get version from tag
      id: get_version
      shell: pwsh
      run: |
        $tag = "${{ github.ref_name }}"
        $version = $tag -replace '^v', ''
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "TAG=$tag" >> $env:GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Http2Client ${{ steps.get_version.outputs.TAG }}"
        files: |
          Http2Client-netstandard2.0.zip
          Http2Client-net5.0.zip
          Http2Client-net6.0.zip
          Http2Client-net8.0.zip
          Http2Client-net9.0.zip
          Http2Client-all-frameworks.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}